### ISSUE TITLE
Bot not executing discord.js functions

### ISSUE THREAD

**Issue by ghost** [MeLlamoPablo/generator-discordbot#3]
the bot is not executing discord.js functions inside the command

```js
var Clapp = require('../modules/clapp-discord');
const Discord = require('discord.js');
var client = new Discord.Client();
const cfg     = require('../../config.js');

module.exports = new Clapp.Command({
  name: "test",
  desc: "???",
  fn: (argv, context) => {
	
	
	client.on('ready', () => {
        client.setPlayingGame('Test Status');
});
	  
  }
});
```

**Comment by MeLlamoPablo** [comment]
You're instantiating a new bot for your command, but the bot that is logged in is the bot that you have in your `index.js`, not your commad file, and therefore, the `ready` event on the client you just declared never fires.

Do not create a new `Discord.Client`. Instead, pass the existing one from `index.js` to your command file through the `context`. Look for this in your `index.js`:

```js
app.parseInput(msg.content, {
      msg: msg
      // Keep adding properties to the context as you need them
});
```

And add the `bot` to the context:

```js
app.parseInput(msg.content, {
      msg: msg,
      client: bot
      // Keep adding properties to the context as you need them
});
```

In your command file, you can reference the client from the context:

```js
var Clapp = require('../modules/clapp-discord');
const cfg     = require('../../config.js');

module.exports = new Clapp.Command({
  name: "test",
  desc: "???",
  fn: (argv, context) => {
	
	
	context.client.setPlayingGame('Test Status');
	  
  }
});
```

Note that you do not need to wait for the `ready` event, as your commad will be executed after an user input, and therefore the client is already `ready` if the command executes.

See [Working with contexts](https://mellamopablo.github.io/clapp/clapp/1.3.0/tutorial-Working-with-contexts.html) in the `clapp` documentation.

**Comment by ghost** [comment]
well this doesnt work either sadly. The NPM output is:

```
    context.client.setPlayingGame('Test Status');
                  ^

TypeError: Cannot read property 'setPlayingGame' of undefined
```

**Comment by MeLlamoPablo** [comment]
Can you please post the contents of `index.js` or link to a repo where I
can find it?

**Comment by ghost** [comment]
https://github.com/SelectPluginDB/siriusbot

**Comment by MeLlamoPablo** [comment]
You didn't commit the whole project to that repo. The `clapp-discord` module is missing and therefore I can't reproduce the issue. Make sure you remove any sensitive information like the Discord API key from `config.js` and then commit the whole project.

The `index.js` looks good by the way, so I'm not sure where the issue is.

**Comment by ghost** [comment]
Added files.

**Comment by MeLlamoPablo** [comment]
I'm getting a different error:

```
> siriusbot@0.0.1 bot /home/pablo/Projects/Node/Tests/siriusbot
> node ./lib/index.js

Running!
/home/pablo/Projects/Node/Tests/siriusbot/lib/commands/verify.js:9
	   context.client.setPlayingGame('Test Status');
	                  ^

TypeError: context.client.setPlayingGame is not a function
    at Command.fn (/home/pablo/Projects/Node/Tests/siriusbot/lib/commands/verify.js:9:20)
    at App.parseInput (/home/pablo/Projects/Node/Tests/siriusbot/node_modules/clapp/dist/App.js:399:24)
    at Client.bot.on.msg (/home/pablo/Projects/Node/Tests/siriusbot/lib/index.js:40:9)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at MessageCreateHandler.handle (/home/pablo/Projects/Node/Tests/siriusbot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/pablo/Projects/Node/Tests/siriusbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/home/pablo/Projects/Node/Tests/siriusbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)
    at WebSocket.onMessage (/home/pablo/Projects/Node/Tests/siriusbot/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/pablo/.nvm/versions/node/v7.9.0/bin/node" "/home/pablo/.nvm/versions/node/v7.9.0/bin/npm" "run" "bot"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! siriusbot@0.0.1 bot: `node ./lib/index.js`
npm ERR! Exit status 1
```

Which means that `verify.js` is actually getting a reference to `index.js`'s `bot`, as expected. However, as the error message says, `setPlayingGame is not a function`. Probably because it doesn't exist, the correct method is [setGame](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setGame). You're probably attempting to use an outdated api.

I'm locking this issue because it is unrelated to `generator-discordbot`. Please refer to [Discord.js's respository](https://github.com/hydrabolt/discord.js) if you have an issue with it, or [Discord.js's community discord](https://discord.gg/bRCvFy9) if you just need help.
